name: Java CI - Reserva Hotel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - name: Dar permisos a Maven Wrapper
      run: chmod +x mvnw

    - name: Compilar y ejecutar pruebas
      run: ./mvnw clean verify

    - name: Generar reporte JaCoCo
      run: ./mvnw jacoco:report

    - name: Ejecutar Checkstyle
      run: ./mvnw checkstyle:check

    - name: Ejecutar SpotBugs
      run: ./mvnw spotbugs:spotbugs

      #prueba

